/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ManagerJFrames;

import GeneralJframes.Login_Manager;
import GeneralJframes.Welcome_Page;
import com.mycompany.universityproject.adminstration;
import com.mycompany.universityproject.arrays;
import static com.mycompany.universityproject.arrays.courses;
import com.mycompany.universityproject.course;
import com.mycompany.universityproject.department;
import com.mycompany.universityproject.faculty;
import com.mycompany.universityproject.instructor;
import com.mycompany.universityproject.student;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmed
 */
public class manDepartments extends javax.swing.JFrame {

    int x, y;
    adminstration s;
    instructor inss;
    student stu;
    course cou;
    faculty facl;
    int i;
    String Stu;
    String Ins;
    String Man;
    String Fac;
    String Cour;
    String perstu;
    String percour;
    String perfacu;
    String perIns;
    String perma;
    double totstu;
    double totins;
    double totman;
    double totfac;
    double totcor;
    double percofstu;
    double percofins;
    double percoffac;
    double percofcor;
    double perofman;
    Login_Manager lo;
    String userr;
    ImageIcon cor = new ImageIcon("src/main/java/images/correct.png");
    ImageIcon warn = new ImageIcon("src/main/java/images/warnicon.png");
    Random random = new Random();

    int randomNumber = random.nextInt(90000) + 1000000;

    /**
     * Creates new form manDepartments
     */
    public manDepartments() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        jTable1.setBackground(new Color(32, 34, 47));
        jTable1.setForeground(Color.WHITE);
        jTable1.setSelectionBackground(Color.GRAY);
        jTable1.setSelectionForeground(Color.WHITE);
        jTable1.setShowGrid(false); // To hide grid lines
        jTable1.setShowVerticalLines(false); // To hide vertical lines
        jTable1.setShowHorizontalLines(false); // To hide horizontal lines

        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(32, 34, 47));
        jTable1.getTableHeader().setForeground(new Color(255, 255, 255));
        jTable1.setRowHeight(50);
        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        nameadd3 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        iddel = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        idfac = new javax.swing.JTextField();
        iddep1 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel70 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        idcor = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel55 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        iddep2 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        idddep = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        idffac = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel64 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel73 = new javax.swing.JLabel();
        idfac2 = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        iddep4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        iddel4 = new javax.swing.JTextField();
        jLabel97 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        iddel5 = new javax.swing.JTextField();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setText("=");
        jLabel43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 390, 50));

        jLabel36.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel36MouseMoved(evt);
            }
        });
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 230, 380, 50));

        nameadd3.setBackground(new java.awt.Color(32, 34, 46));
        nameadd3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        nameadd3.setForeground(new java.awt.Color(255, 255, 255));
        nameadd3.setToolTipText("");
        nameadd3.setBorder(null);
        nameadd3.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        nameadd3.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        nameadd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameadd3ActionPerformed(evt);
            }
        });
        jPanel9.add(nameadd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 260, 20));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel9.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 260, 10));

        jLabel60.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\312.png")); // NOI18N
        jPanel9.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 40));

        jLabel61.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Addition ?-");
        jPanel9.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 320, 80));

        jLabel62.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("-  Name  :-");
        jPanel9.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 115, -1, 30));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("+");
        jPanel9.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 30));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Add Faculty");
        jPanel9.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel67.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\305.png")); // NOI18N
        jPanel9.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel68.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\blockfac3.png")); // NOI18N
        jPanel9.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 690, 390, 280));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(31, 34, 46));
        jPanel8.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel8MouseMoved(evt);
            }
        });
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        home.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\homeic.png")); // NOI18N

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Home");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 480, 70));

        jPanel19.setBackground(new java.awt.Color(204, 0, 51));
        jPanel19.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel19MouseMoved(evt);
            }
        });
        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel19MouseClicked(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Log out");

        jLabel47.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\couric.png")); // NOI18N

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel47)
                .addGap(18, 18, 18)
                .addComponent(jLabel46)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 950, 480, 70));

        jPanel15.setBackground(new java.awt.Color(31, 34, 46));
        jPanel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel15MouseMoved(evt);
            }
        });
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\instruic.png")); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Instructors");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 480, 70));

        jPanel14.setBackground(new java.awt.Color(31, 34, 46));
        jPanel14.setDoubleBuffered(false);
        jPanel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel14MouseMoved(evt);
            }
        });
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\univic.png")); // NOI18N

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Faculties");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 480, 70));

        jPanel16.setBackground(new java.awt.Color(153, 153, 153));
        jPanel16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel16MouseMoved(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\departico.png")); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Departments");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16))
        );

        jPanel3.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 480, 70));

        jPanel17.setBackground(new java.awt.Color(31, 34, 46));
        jPanel17.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel17MouseMoved(evt);
            }
        });
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel17MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cources");

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\couric.png")); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 480, 70));

        jPanel18.setBackground(new java.awt.Color(31, 34, 46));
        jPanel18.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel18MouseMoved(evt);
            }
        });
        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel18MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\studic.png")); // NOI18N

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Students");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 780, 480, 80));

        user1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        user1.setForeground(new java.awt.Color(255, 255, 255));
        user1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                user1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 200, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\manic.png")); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\pan_1.png")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1110));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 1110));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        jPanel6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, 10));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 51, 102));
        jLabel33.setText("-Deoartment");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 40));

        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 230, 200, 50));

        jLabel75.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("DEL? -");
        jPanel6.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 80));

        jLabel27.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("- ID SET  :-");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Delete Department");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, -1));

        iddel.setBackground(new java.awt.Color(31, 34, 46));
        iddel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        iddel.setForeground(new java.awt.Color(255, 255, 255));
        iddel.setBorder(null);
        iddel.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        iddel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddelActionPerformed(evt);
            }
        });
        jPanel6.add(iddel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 80, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\304.png")); // NOI18N
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\blockfac4.png")); // NOI18N
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 102));
        jLabel30.setText("ADD");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 690, 220, 280));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 102));
        jLabel24.setText("ADD?");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, 40));

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\313.png")); // NOI18N
        jLabel32.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel32MouseMoved(evt);
            }
        });
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 230, 380, 50));

        idfac.setBackground(new java.awt.Color(32, 34, 46));
        idfac.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        idfac.setForeground(new java.awt.Color(255, 0, 102));
        idfac.setToolTipText("");
        idfac.setBorder(null);
        idfac.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        idfac.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        idfac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfacActionPerformed(evt);
            }
        });
        jPanel5.add(idfac, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 70, 20));

        iddep1.setBackground(new java.awt.Color(32, 34, 46));
        iddep1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        iddep1.setForeground(new java.awt.Color(204, 0, 102));
        iddep1.setToolTipText("");
        iddep1.setBorder(null);
        iddep1.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        iddep1.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        iddep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddep1ActionPerformed(evt);
            }
        });
        jPanel5.add(iddep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 100, 20));

        jSeparator9.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator9.setForeground(new java.awt.Color(51, 51, 51));
        jPanel5.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 100, 10));

        jSeparator8.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator8.setForeground(new java.awt.Color(51, 51, 51));
        jPanel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 70, 10));

        jLabel70.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("-  ID DEP  ");
        jPanel5.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 85, -1, 30));

        jLabel69.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("-  ID FAC ");
        jPanel5.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 85, -1, 30));

        jLabel57.setBackground(new java.awt.Color(204, 0, 153));
        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 51, 102));
        jLabel57.setText(" REF.");
        jPanel5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 100, 60, 70));

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\316.png")); // NOI18N
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 40));

        jLabel44.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Faculties  -");
        jPanel5.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, 80));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("+");
        jPanel5.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Add Department");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 240, 180, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\314.png")); // NOI18N
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 100));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\blockfac3.png")); // NOI18N
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -300, -1, 580));

        jLabel56.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("-  Name  :-");
        jPanel5.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 690, 390, 130));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel58.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\316.png")); // NOI18N
        jLabel58.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel58MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel58MouseEntered(evt);
            }
        });
        jPanel7.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 40));

        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\313.png")); // NOI18N
        jLabel35.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel35MouseMoved(evt);
            }
        });
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 230, 380, 50));

        idcor.setBackground(new java.awt.Color(32, 34, 46));
        idcor.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        idcor.setForeground(new java.awt.Color(255, 255, 255));
        idcor.setToolTipText("");
        idcor.setBorder(null);
        idcor.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        idcor.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        idcor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcorActionPerformed(evt);
            }
        });
        jPanel7.add(idcor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 70, 20));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 70, 10));

        jLabel55.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("-  ID DEP  ");
        jPanel7.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 85, -1, 30));

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        jPanel7.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 90, 10));

        iddep2.setBackground(new java.awt.Color(32, 34, 46));
        iddep2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        iddep2.setForeground(new java.awt.Color(255, 255, 255));
        iddep2.setToolTipText("");
        iddep2.setBorder(null);
        iddep2.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        iddep2.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        iddep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddep2ActionPerformed(evt);
            }
        });
        jPanel7.add(iddep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 90, 20));

        jLabel51.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Courses -");
        jPanel7.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, 80));

        jLabel39.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("-  ID COR ");
        jPanel7.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 85, -1, 30));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 0, 102));
        jLabel59.setText("ADD?");
        jPanel7.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 40, 40));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("+");
        jPanel7.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 30));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Add Department");
        jPanel7.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 240, 180, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\314.png")); // NOI18N
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -160, 440, 440));

        jLabel54.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\blockfac3.png")); // NOI18N
        jPanel7.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -300, 450, 580));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 840, 390, 130));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoscrolls(false);
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(32, 34, 46));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 180, 1330, 440));

        jLabel40.setBackground(new java.awt.Color(204, 0, 153));
        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 51, 102));
        jLabel40.setText("with their important data");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 280, 60));

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\ref.png")); // NOI18N
        jLabel31.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel31MouseMoved(evt);
            }
        });
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 90, 40, 40));

        jLabel48.setBackground(new java.awt.Color(204, 0, 153));
        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 51, 102));
        jLabel48.setText(" REF.");
        jPanel4.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 100, 60, 70));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Departments");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 430, 90));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\blockfac1.png")); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel50.setBackground(new java.awt.Color(204, 0, 153));
        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 51, 102));
        jLabel50.setText("with their important data");
        jPanel4.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, 70));

        jLabel34.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\309.png")); // NOI18N
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(-380, 120, 1870, 550));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 1300, 610));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idddep.setBackground(new java.awt.Color(32, 34, 46));
        idddep.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        idddep.setForeground(new java.awt.Color(255, 255, 255));
        idddep.setToolTipText("");
        idddep.setBorder(null);
        idddep.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        idddep.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        idddep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idddepActionPerformed(evt);
            }
        });
        jPanel11.add(idddep, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, 20));

        jSeparator12.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator12.setForeground(new java.awt.Color(51, 51, 51));
        jPanel11.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 110, 10));

        idffac.setBackground(new java.awt.Color(32, 34, 46));
        idffac.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        idffac.setForeground(new java.awt.Color(255, 255, 255));
        idffac.setToolTipText("");
        idffac.setBorder(null);
        idffac.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        idffac.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        idffac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idffacActionPerformed(evt);
            }
        });
        jPanel11.add(idffac, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 110, 20));

        jSeparator10.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator10.setForeground(new java.awt.Color(51, 51, 51));
        jPanel11.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, 10));

        jLabel64.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 51, 51));
        jLabel64.setText("  Faculty -");
        jPanel11.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 150, 60));

        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 5, 30, 120));

        jLabel65.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\323.png")); // NOI18N
        jPanel11.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, -30, 750, 190));

        jLabel72.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("-  ID DEP :-");
        jPanel11.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 20));

        jLabel71.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("-  ID FAC :- ");
        jPanel11.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 40));

        jLabel49.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText(" DEL ");
        jPanel11.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 60));

        jLabel81.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\blockfac4.png")); // NOI18N
        jPanel11.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, -20, 550, 300));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 690, 250, 130));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\del.png")); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 25, -1, -1));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 5, 30, 120));

        jSeparator13.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator13.setForeground(new java.awt.Color(51, 51, 51));
        jPanel13.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 260, 20));

        jSeparator11.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator11.setForeground(new java.awt.Color(51, 51, 51));
        jPanel13.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, 10));

        jLabel73.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("-  ID Cour :- ");
        jPanel13.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 40));

        idfac2.setBackground(new java.awt.Color(32, 34, 46));
        idfac2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        idfac2.setForeground(new java.awt.Color(255, 255, 255));
        idfac2.setToolTipText("");
        idfac2.setBorder(null);
        idfac2.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        idfac2.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        idfac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfac2ActionPerformed(evt);
            }
        });
        jPanel13.add(idfac2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 110, 20));

        jLabel74.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("-  ID DEP :-");
        jPanel13.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, -1));

        jSeparator15.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator15.setForeground(new java.awt.Color(51, 51, 51));
        jPanel13.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 110, 10));

        iddep4.setBackground(new java.awt.Color(32, 34, 46));
        iddep4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        iddep4.setForeground(new java.awt.Color(255, 255, 255));
        iddep4.setToolTipText("");
        iddep4.setBorder(null);
        iddep4.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        iddep4.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        iddep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddep4ActionPerformed(evt);
            }
        });
        jPanel13.add(iddep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 100, 20));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\324.png")); // NOI18N
        jPanel13.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, -30, 780, 190));

        jLabel77.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 102, 0));
        jLabel77.setText(" Course -");
        jPanel13.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, 40));

        jLabel76.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("DEL");
        jPanel13.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 40));

        jLabel92.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel92MouseMoved(evt);
            }
        });
        jLabel92.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel92MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 390, 50));

        jLabel94.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(255, 255, 255));
        jLabel94.setText("Delete Department");
        jPanel13.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 240, 200, -1));

        jLabel95.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(255, 255, 255));
        jLabel95.setText("-");
        jPanel13.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 30));

        iddel4.setBackground(new java.awt.Color(31, 34, 46));
        iddel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        iddel4.setForeground(new java.awt.Color(255, 255, 255));
        iddel4.setBorder(null);
        iddel4.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        iddel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddel4ActionPerformed(evt);
            }
        });
        jPanel13.add(iddel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 260, -1));

        jLabel97.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\blockfac4.png")); // NOI18N
        jPanel13.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, -1, -1));

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator14.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator14.setForeground(new java.awt.Color(51, 51, 51));
        jPanel20.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 260, 20));

        jLabel98.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\313.png")); // NOI18N
        jPanel20.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 40));

        jLabel99.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(255, 255, 255));
        jLabel99.setText("Deletion  :-");
        jPanel20.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 320, 80));

        jLabel100.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel100MouseMoved(evt);
            }
        });
        jLabel100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel100MouseClicked(evt);
            }
        });
        jPanel20.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 390, 50));

        jLabel101.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(255, 255, 255));
        jLabel101.setText("- ID SET  :-");
        jPanel20.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel102.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(255, 255, 255));
        jLabel102.setText("Delete Department");
        jPanel20.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 240, 200, -1));

        jLabel103.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(255, 255, 255));
        jLabel103.setText("-");
        jPanel20.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 30));

        iddel5.setBackground(new java.awt.Color(31, 34, 46));
        iddel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        iddel5.setForeground(new java.awt.Color(255, 255, 255));
        iddel5.setBorder(null);
        iddel5.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        iddel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddel5ActionPerformed(evt);
            }
        });
        jPanel20.add(iddel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 260, -1));

        jLabel104.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\304.png")); // NOI18N
        jPanel20.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel105.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\blockfac4.png")); // NOI18N
        jPanel20.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel13.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 690, 210, 280));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 840, 250, 130));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\BACK.png")); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 1560, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1926, 1020);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseClicked
        new studentman().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jPanel18MouseClicked

    private void jPanel18MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseMoved
        setcolor(jPanel18);
        resetcolor(jPanel16);
        resetcolor(jPanel15);
        resetcolor(jPanel17);
        resetcolor(jPanel14);
        resetcolor(jPanel8);
        jPanel18.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel18MouseMoved
    public static String listToString(List<?> list) {
        String result = "";
        for (int i = 0; i < list.size(); i++) {
            result += " " + list.get(i);
        }
        return result;
    }
    private void jPanel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseClicked
        new Courcesman().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jPanel17MouseClicked

    private void jPanel17MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseMoved
        setcolor(jPanel17);
        resetcolor(jPanel16);
        resetcolor(jPanel15);
        resetcolor(jPanel14);
        resetcolor(jPanel18);
        resetcolor(jPanel8);
        jPanel17.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel17MouseMoved
    private void jPanel16MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseMoved
        setcolor(jPanel16);
        resetcolor(jPanel14);
        resetcolor(jPanel15);
        resetcolor(jPanel17);
        resetcolor(jPanel18);
        resetcolor(jPanel8);
        jPanel16.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel16MouseMoved
    public class AlternateRowRenderer extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            if (row % 2 == 0) {
                c.setBackground(new Color(32, 34, 47));
            } else {
                c.setBackground(new Color(0, 0, 0));
            }
            c.setForeground(Color.WHITE);

            return c;
        }
    }


    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        new facultyman().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jPanel14MouseClicked
    public int totDep() {
        int totDep = 0;
        for (i = 0; i < arrays.dep.length; i++) {
            if (arrays.getDep()[i] != null) {
                totDep++;

            }
        }
        return totDep;
    }

    private void jPanel14MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseMoved

        setcolor(jPanel14);
        resetcolor(jPanel16);
        resetcolor(jPanel15);
        resetcolor(jPanel17);
        resetcolor(jPanel18);
        resetcolor(jPanel8);

        jPanel14.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel14MouseMoved
private void populateTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    jTable1.setDefaultRenderer(Object.class, new manDepartments.AlternateRowRenderer());
    String[] columnNames = {"Department Name", "ID", "Faculties", "Courses"};
    model.setColumnIdentifiers(columnNames);

    for (int s = 0; s < arrays.dep.length; s++) {
        if (arrays.dep[s] != null) {
            List<String> facul = new ArrayList<>();
            List<String> courseList = new ArrayList<>();

            for (int m = 0; m < arrays.dep[s].getFacultys().size(); m++) {
                faculty faculties = arrays.dep[s].getFacultys().get(m);
                facul.add(faculties.getName());
            }

            for (int b = 0; b < arrays.dep[s].getCourses().size(); b++) {
                course courses = arrays.dep[s].getCourses().get(b);
                courseList.add(courses.getCoursename());
            }

            // Convert the ArrayLists to comma-separated strings
            String facultiesString = String.join(", ", facul);
            String courseString = String.join(", ", courseList);

            Object[] rowData = {
                "  -  " + arrays.dep[s].getName(),
                "   -  " + arrays.dep[s].getId(),
                " -  " + facultiesString,
                " -  " + courseString
            };
            model.addRow(rowData);
        }
    }

}
    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        new instructorman().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jPanel15MouseClicked

    private void jPanel15MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseMoved
        setcolor(jPanel15);
        resetcolor(jPanel16);
        resetcolor(jPanel14);
        resetcolor(jPanel17);
        resetcolor(jPanel18);
        resetcolor(jPanel8);
        jPanel15.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel15MouseMoved

    private void jPanel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseClicked
        new Welcome_Page().setVisible(true);
        new Login_Manager().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jPanel19MouseClicked

    private void jPanel19MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseMoved
        jPanel19.setBackground(new Color(153, 0, 0));

        jPanel19.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel19MouseMoved

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        new Managerpage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseMoved
        setcolor(jPanel8);
        resetcolor(jPanel14);
        resetcolor(jPanel15);
        resetcolor(jPanel17);
        resetcolor(jPanel18);
        resetcolor(jPanel16);

        jPanel8.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel8MouseMoved
    // public department(int id, String name) {

    private void iddelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddelActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        /*DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String[] columnNames = {"UserName", "Faculty", "ID"};
        model.setColumnIdentifiers(columnNames);

        for (student ss : Students) {
            if (ss != null) {
                Object[] rowData = {ss.getUsername(), ss.getFaculty(), ss.getId()};
                model.addRow(rowData);
            }
        }

        JScrollPane scrollPane = new JScrollPane(jTable1);
        jPanel4.add(scrollPane);
         */
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jLabel31MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseMoved
        jLabel31.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel31MouseMoved

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        setVisible(false);
        new manDepartments().setVisible(true);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel32MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseMoved
        jLabel32.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel32MouseMoved

    private void jLabel35MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel35MouseMoved

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel35MouseClicked

    private void idcorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcorActionPerformed

    private void iddep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddep2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddep2ActionPerformed

    private void jLabel36MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseMoved
        jLabel32.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel36MouseMoved

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked

    }//GEN-LAST:event_jLabel36MouseClicked

    private void nameadd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameadd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameadd3ActionPerformed

    private void iddep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddep1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddep1ActionPerformed

    private void idfacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfacActionPerformed

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
    try {
        int idfacc = Integer.parseInt(idfac.getText());
        int iddepp = Integer.parseInt(iddep1.getText());
        int indexfac = -1;
        int indexdep = -1;

        for (int i = 0; i < arrays.fac.length; i++) {
            if (arrays.getFac()[i] != null && arrays.getFac()[i].getId() == idfacc) {
                indexfac = i;
                break;
            }
        }

        for (int i = 0; i < arrays.dep.length; i++) {
            if (arrays.dep[i] != null && arrays.getDep()[i].getId() == iddepp) {
                indexdep = i;
                break;
            }
        }

        if (indexfac != -1 && indexdep != -1) {
            List<faculty> faculties = arrays.getDep()[indexdep].getFacultys();
            faculties.add(arrays.fac[indexfac]);
            arrays.getDep()[indexdep].setFacultys((ArrayList<faculty>) faculties);
                            JOptionPane.showMessageDialog(null, "Faculty has been Added successfully. Refresh the table to check.", "Important Note", HEIGHT, cor);

            populateTable(); // Refresh the table with updated data
        } else {
            JOptionPane.showMessageDialog(null, "Sorry, an Error Occurred!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (java.lang.NumberFormatException ssss) {
        JOptionPane.showMessageDialog(null, "Sorry, an Error Occurred!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (java.lang.NullPointerException asd ) {
                JOptionPane.showMessageDialog(null, "Sorry, an Error Occurred!", "Error", JOptionPane.ERROR_MESSAGE);

    }
        
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel92MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel92MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel92MouseMoved

    private void jLabel92MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel92MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel92MouseClicked

    private void jLabel100MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel100MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel100MouseMoved

    private void jLabel100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel100MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel100MouseClicked

    private void iddel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddel5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddel5ActionPerformed

    private void idfac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfac2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfac2ActionPerformed

    private void iddep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddep4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddep4ActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
                try {
            if (iddel.getText().equals("")) {
                            JOptionPane.showMessageDialog(null, "Please Enter the ID of Faculty ! Error Code :- 03X2xxD", "Importanat Note", HEIGHT, warn);
            }
            else {
        int m = Integer.parseInt(iddel.getText()) ;

        for (int i = 0; i < arrays.dep.length; i++) {
            if (arrays.dep[i].getId() == m) {
       arrays.dep[i] = null ; 
                   JOptionPane.showMessageDialog(null, "Faculty Has been Deleted Correctly ,Refresh the table to check it ", "Importanat Note", HEIGHT, cor);
break ; 
            }
                }
                }
                }
            catch (java.lang.NullPointerException cat ) {
                                       JOptionPane.showMessageDialog(null, " This Faculty isn't set , Please Check Data , Error Code :- EXep2442x ", "Importanat Note", HEIGHT, warn);

                    }
                catch (java.lang.NumberFormatException sda) {
                                                           JOptionPane.showMessageDialog(null, " ID should be numbers only ! , Error Code :- EXep42142x ", "Importanat Note", HEIGHT, warn);

                }         
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseClicked
    try {
        int idcoor = Integer.parseInt(idcor.getText());
        int iddepp = Integer.parseInt(iddep2.getText());
        int indexcor = -1;
        int indexdep = -1;

        for (int i = 0; i < arrays.courses.length; i++) {
            if (arrays.getCourses()[i].getCourseCode() == idcoor) {
                indexcor = i;
                break;
            }
        }

        for (int i = 0; i < arrays.dep.length; i++) {
            if (arrays.getDep()[i].getId() == iddepp) {
                indexdep = i;
                break;
            }
        }

        if (indexcor != -1 && indexdep != -1) {
            ArrayList<course> Courses = arrays.getDep()[indexdep].getCourses() ;
            Courses.add(arrays.courses[indexcor]);
            arrays.getDep()[indexdep].setCourses((ArrayList<course>) Courses);
                            JOptionPane.showMessageDialog(null, "Course has been Added successfully. Refresh the table to check.", "Important Note", HEIGHT, cor);

            populateTable(); // Refresh the table with updated data
        } else {
            JOptionPane.showMessageDialog(null, "Sorry, an Error Occurred!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (java.lang.NumberFormatException ssss) {
        JOptionPane.showMessageDialog(null, "Sorry, an Error Occurred!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (java.lang.NullPointerException asdss ) {
                JOptionPane.showMessageDialog(null, "Sorry, an Error Occurred!", "Error", JOptionPane.ERROR_MESSAGE);

    }
    }//GEN-LAST:event_jLabel58MouseClicked

    private void jLabel58MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel58MouseEntered

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
               if (nameadd3.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter the name of Faculty ! Error Code :- 00X2xxD", "Importanat Note", HEIGHT, warn);
               }
            else {
        int index = -1;
        for (int i = 0; i < arrays.dep.length; i++) {
            if (arrays.dep[i] == null) {
                index = i;
                break;
            }
        }
        if (index != -1) {
            department dep = new department(randomNumber, nameadd3.getText());
            arrays.dep[index] = dep;
            String message = "Your Department ID IS :-  " + Integer.toString(randomNumber);
            JOptionPane.showMessageDialog(null, "Department Has been added Correctly ,Refresh the table to check it ", "Importanat Note", HEIGHT, cor);
            JOptionPane.showMessageDialog(null, message, "Importanat Note", HEIGHT, warn);
        } else {
            JOptionPane.showMessageDialog(null, "Sorry , an Error Occured !", "Error", JOptionPane.ERROR_MESSAGE);

        }
            }
    }//GEN-LAST:event_jLabel43MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        try {
            if (idfac2.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Enter the ID of Faculty!", "Important Note", HEIGHT, warn);
            } else if (iddep4.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Enter the ID of Department!", "Important Note", HEIGHT, warn);
            } else {
                int corId = Integer.parseInt(idfac2.getText());
                int departmentId = Integer.parseInt(iddep4.getText());
                int departmentIndex = -1;
                int corIndex = -1;

                // Find the department index
                for (int i = 0; i < arrays.dep.length; i++) {
                    if (arrays.dep[i] != null && arrays.dep[i].getId() == departmentId) {
                        departmentIndex = i;
                        break;
                    }
                }

                // Find the faculty index within the department
                if (departmentIndex != -1) {
                    List<course> courses = arrays.dep[departmentIndex].getCourses() ;
                    for (int i = 0; i < courses.size(); i++) {
                        if (courses.get(i).getCourseCode() == corId) {
                            corIndex = i;
                            break;
                        }
                    }
                }

                // Delete the faculty if found
                if (departmentIndex != -1 && corIndex != -1) {
                    List<course> courses = arrays.dep[departmentIndex].getCourses() ;
                    courses.remove(corIndex);
                    arrays.dep[departmentIndex].setCourses((ArrayList<course>) courses);
                    populateTable(); // Refresh the table with updated data
                    JOptionPane.showMessageDialog(null, "Course has been deleted successfully. Refresh the table to check.", "Important Note", HEIGHT, cor);
                } else {
                    JOptionPane.showMessageDialog(null, "Course or Department not found!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (java.lang.NumberFormatException sda) {
            JOptionPane.showMessageDialog(null, "ID should be numbers only!", "Important Note", HEIGHT, warn);
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        try {
            if (idffac.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Enter the ID of Faculty!", "Important Note", HEIGHT, warn);
            } else if (idddep.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Enter the ID of Department!", "Important Note", HEIGHT, warn);
            } else {
                int facultyId = Integer.parseInt(idffac.getText());
                int departmentId = Integer.parseInt(idddep.getText());
                int departmentIndex = -1;
                int facultyIndex = -1;

                // Find the department index
                for (int i = 0; i < arrays.dep.length; i++) {
                    if (arrays.dep[i] != null && arrays.dep[i].getId() == departmentId) {
                        departmentIndex = i;
                        break;
                    }
                }

                // Find the faculty index within the department
                if (departmentIndex != -1) {
                    List<faculty> faculties = arrays.dep[departmentIndex].getFacultys();
                    for (int i = 0; i < faculties.size(); i++) {
                        if (faculties.get(i).getId() == facultyId) {
                            facultyIndex = i;
                            break;
                        }
                    }
                }

                // Delete the faculty if found
                if (departmentIndex != -1 && facultyIndex != -1) {
                    List<faculty> faculties = arrays.dep[departmentIndex].getFacultys();
                    faculties.remove(facultyIndex);
                    arrays.dep[departmentIndex].setFacultys((ArrayList<faculty>) faculties);
                    populateTable(); // Refresh the table with updated data
                    JOptionPane.showMessageDialog(null, "Faculty has been deleted successfully. Refresh the table to check.", "Important Note", HEIGHT, cor);
                } else {
                    JOptionPane.showMessageDialog(null, "Faculty or Department not found!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (java.lang.NumberFormatException sda) {
            JOptionPane.showMessageDialog(null, "ID should be numbers only!", "Important Note", HEIGHT, warn);
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void idffacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idffacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idffacActionPerformed

    private void idddepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idddepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idddepActionPerformed

    private void iddel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddel4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddel4ActionPerformed

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
      try {
            if (idffac.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Enter the ID of Faculty!", "Important Note", HEIGHT, warn);
            } else if (idddep.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Enter the ID of Department!", "Important Note", HEIGHT, warn);
            } else {
                int corfac = Integer.parseInt(idffac.getText());
                int departmentId = Integer.parseInt(idddep.getText());
                int departmentIndex = -1;
                int facIndex = -1;

                // Find the department index
                for (int i = 0; i < arrays.dep.length; i++) {
                    if (arrays.dep[i] != null && arrays.dep[i].getId() == departmentId) {
                        departmentIndex = i;
                        break;
                    }
                }

                // Find the faculty index within the department
                if (departmentIndex != -1) {
                    List<faculty> faculties = arrays.dep[departmentIndex].getFacultys() ;
                    for (int i = 0; i < faculties.size(); i++) {
                        if (faculties.get(i).getId() == corfac) {
                            facIndex = i;
                            break;
                        }
                    }
                }

                // Delete the faculty if found
                if (departmentIndex != -1 && facIndex != -1) {
                    List<faculty> faculties = arrays.dep[departmentIndex].getFacultys() ;
                    faculties.remove(facIndex);
                    arrays.dep[departmentIndex].setFacultys((ArrayList<faculty>) faculties);
                    populateTable(); // Refresh the table with updated data
                    JOptionPane.showMessageDialog(null, "Course has been deleted successfully. Refresh the table to check.", "Important Note", HEIGHT, cor);
                } else {
                    JOptionPane.showMessageDialog(null, "Course or Department not found!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
    } catch (java.lang.NumberFormatException sda) {
         JOptionPane.showMessageDialog(null, "ID should be numbers only!", "Important Note", HEIGHT, warn);
    }
    }//GEN-LAST:event_jLabel37MouseClicked

    private void user1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_user1AncestorAdded
        try {
            userr = arrays.admins[Login_Manager.getM()].getUsername();
            user1.setText(userr);
        } catch (java.lang.NullPointerException sww) {
        }

        /*
        try {
            user () ;
            user.setText(adminstration.admins[m].getUsername());
        } catch ( java.lang.StackOverflowError ss ) {
        }
        */
    }//GEN-LAST:event_user1AncestorAdded

    void setcolor(JPanel s) {
        s.setBackground(new Color(153, 153, 153));
    }

    void resetcolor(JPanel m) {
        m.setBackground(new Color(31, 34, 46));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manDepartments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manDepartments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manDepartments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manDepartments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new manDepartments().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel home;
    private javax.swing.JTextField idcor;
    private javax.swing.JTextField idddep;
    private javax.swing.JTextField iddel;
    private javax.swing.JTextField iddel4;
    private javax.swing.JTextField iddel5;
    private javax.swing.JTextField iddep1;
    private javax.swing.JTextField iddep2;
    private javax.swing.JTextField iddep4;
    private javax.swing.JTextField idfac;
    private javax.swing.JTextField idfac2;
    private javax.swing.JTextField idffac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameadd3;
    private javax.swing.JLabel user1;
    // End of variables declaration//GEN-END:variables
}
