/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StudentJFrames;

import GeneralJframes.Login_Student;
import GeneralJframes.Welcome_Page;
import ManagerJFrames.Courcesman;
import ManagerJFrames.instructorman;
import com.mycompany.universityproject.arrays;
import com.mycompany.universityproject.course;
import com.mycompany.universityproject.department;
import com.mycompany.universityproject.student;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmed
 */
public class studentDash extends javax.swing.JFrame {

    String userr;
    Login_Student lo;
    ImageIcon cor = new ImageIcon("src/main/java/images/correct.png");
    ImageIcon warn = new ImageIcon("src/main/java/images/warnicon.png");

    /**
     * Creates new form studentdash
     */
    public studentDash() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        jTable1.setBackground(new Color(32, 34, 47));
        jTable1.setForeground(Color.WHITE);
        jTable1.setSelectionBackground(Color.GRAY);
        jTable1.setSelectionForeground(Color.WHITE);
        jTable1.setShowGrid(false); // To hide grid lines
        jTable1.setShowVerticalLines(false); // To hide vertical lines
        jTable1.setShowHorizontalLines(false); // To hide horizontal lines

        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(32, 34, 47));
        jTable1.getTableHeader().setForeground(new Color(255, 255, 255));
        jTable1.setRowHeight(50);
       populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        fac4 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        fac3 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        fac1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        fac = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        fac2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fac4.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        fac4.setForeground(new java.awt.Color(255, 255, 255));
        fac4.setText("2018");
        fac4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                fac4AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel12.add(fac4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 240, 90));

        jLabel55.setBackground(new java.awt.Color(204, 0, 153));
        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 51, 102));
        jLabel55.setText("EnrolledYear");
        jPanel12.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 130, 60));

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\Untitled-2.png")); // NOI18N
        jPanel12.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel64.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\313.png")); // NOI18N
        jLabel64.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel64MouseMoved(evt);
            }
        });
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel64MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 230, 380, 50));

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\336.png")); // NOI18N
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -86, -1, 370));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("+");
        jPanel12.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 30));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Add Department");
        jPanel12.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 240, 180, -1));

        jLabel73.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\335.png")); // NOI18N
        jPanel12.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 450, 350));

        back.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 760, 410, 230));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\334.png")); // NOI18N
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -116, 420, 400));

        jLabel54.setBackground(new java.awt.Color(204, 0, 153));
        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 51, 102));
        jLabel54.setText(" GPA  ");
        jPanel11.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 50, 80));

        fac3.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        fac3.setForeground(new java.awt.Color(255, 255, 255));
        fac3.setText("0.0");
        fac3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                fac3AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel11.add(fac3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 240, 130));

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\Untitled-2.png")); // NOI18N
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 90));

        jLabel63.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\313.png")); // NOI18N
        jLabel63.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel63MouseMoved(evt);
            }
        });
        jLabel63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel63MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 230, 380, 50));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("+");
        jPanel11.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 30));

        jLabel69.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Add Department");
        jPanel11.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 240, 180, -1));

        jLabel71.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\335.png")); // NOI18N
        jPanel11.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 420, 270));

        back.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 520, 410, 220));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\310.png")); // NOI18N
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jLabel51.setBackground(new java.awt.Color(204, 0, 153));
        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 51, 102));
        jLabel51.setText("FACULTY");
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 230, 70));

        fac1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        fac1.setForeground(new java.awt.Color(255, 255, 255));
        fac1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                fac1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(fac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 280, 90));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\Untitled-2.png")); // NOI18N
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\block-fac-2.png")); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        back.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 200, 390, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\326.png")); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jLabel49.setBackground(new java.awt.Color(204, 0, 153));
        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 51, 102));
        jLabel49.setText("ID SET");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 230, 70));

        fac.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        fac.setForeground(new java.awt.Color(255, 255, 255));
        fac.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                facAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(fac, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 240, 90));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\Untitled-2.png")); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\block-fac-2.png")); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        back.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 390, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\334.png")); // NOI18N
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -190, -1, 680));

        jLabel53.setBackground(new java.awt.Color(204, 0, 153));
        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 51, 102));
        jLabel53.setText("Number of Courses ");
        jPanel4.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 230, 70));

        fac2.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        fac2.setForeground(new java.awt.Color(255, 255, 255));
        fac2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                fac2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel4.add(fac2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 240, 90));

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\Untitled-2.png")); // NOI18N
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\332.png")); // NOI18N
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        back.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 200, 410, 290));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoscrolls(false);
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(32, 34, 46));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 160, 930, 320));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\327.png")); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -580, 910, 760));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\ref.png")); // NOI18N
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 50, 50));

        jLabel48.setBackground(new java.awt.Color(204, 0, 153));
        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 51, 102));
        jLabel48.setText(" REF.");
        jPanel5.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 60, 70));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Courses Set");
        jPanel5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 380, 90));

        jLabel37.setBackground(new java.awt.Color(204, 0, 153));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 51, 102));
        jLabel37.setText("with their important data");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, 70));

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\block5.png")); // NOI18N
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel39.setBackground(new java.awt.Color(204, 0, 153));
        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 51, 102));
        jLabel39.setText("with their important data");
        jPanel5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, 70));

        back.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 840, 470));

        jLabel45.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\qr.png")); // NOI18N
        back.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1740, 70, -1, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 153, 153));
        jLabel44.setText("Student Dashboard");
        back.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        jLabel43.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Welcome Back");
        back.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\BACK.png")); // NOI18N
        jLabel15.setText("jLabel15");
        back.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 1560, 1020));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setForeground(new java.awt.Color(153, 153, 153));
        jPanel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel8MouseMoved(evt);
            }
        });
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        home.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\homeic.png")); // NOI18N

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Home");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 480, 70));

        jPanel19.setBackground(new java.awt.Color(255, 0, 51));
        jPanel19.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel19MouseMoved(evt);
            }
        });
        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel19MouseClicked(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Log out");

        jLabel47.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\couric.png")); // NOI18N

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel47)
                .addGap(18, 18, 18)
                .addComponent(jLabel46)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 950, 480, 70));

        jPanel15.setBackground(new java.awt.Color(31, 34, 46));
        jPanel15.setForeground(new java.awt.Color(31, 34, 46));
        jPanel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel15MouseMoved(evt);
            }
        });
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("about");

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\info.png")); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel9))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 480, 80));

        jPanel14.setBackground(new java.awt.Color(31, 34, 46));
        jPanel14.setDoubleBuffered(false);
        jPanel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel14MouseMoved(evt);
            }
        });
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\couric.png")); // NOI18N

        jLabel5.setBackground(new java.awt.Color(31, 34, 46));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Courses");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 480, 70));

        user1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        user1.setForeground(new java.awt.Color(255, 255, 255));
        user1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                user1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 200, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\studeic.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Documents\\NetBeansProjects\\UniversityProject\\src\\main\\java\\images\\studentpage.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1110));

        back.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 1110));

        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1020));

        setBounds(0, 0, 1920, 1020);
    }// </editor-fold>//GEN-END:initComponents
    public class AlternateRowRenderer extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            if (row % 2 == 0) {
                c.setBackground(new Color(32, 34, 47));
            } else {
                c.setBackground(new Color(0, 0, 0));
            }
            c.setForeground(Color.WHITE);

            return c;
        }
    }

    void setcolor(JPanel s) {
        s.setBackground(new Color(153, 153, 153));
    }

    void resetcolor(JPanel m) {
        m.setBackground(new Color(31, 34, 46));

    }
//            }        for (int s = 0; s < arrays.Students.length; s++) {
//            if (arrays.Students[s] != null) {
//                List<String> cn = new ArrayList<>();
//                List<String> cid = new ArrayList<>();
//                List<String> credit = new ArrayList<>();
//                List<String> cGPA = new ArrayList<>();

private void populateTable() {

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    jTable1.setDefaultRenderer(Object.class, new studentDash.AlternateRowRenderer());
    String[] columnNames = {"ID", "Name", "Credit", " GPA "};
    model.setColumnIdentifiers(columnNames);
//    for (int s = 0; s < arrays.courses.length; s++) {
//        if (arrays.courses[s] != null && arrays.Students[s].getCourses().get(s) != null&& arrays.Students[s].getCourses().get(s).getCourseCode() == arrays.courses[s].getCourseCode()) {
//            List<String> courseprereq = new ArrayList<>();
//
//            for (int m = 0; m < arrays.courses[s].getPrerequist().size(); m++) {
//                course Course = arrays.courses[s].getPrerequist().get(m);
//                courseprereq.add(Course.getCoursename());
//            }
student s = arrays.Students[Login_Student.getM()] ;
          
//            // Convert the ArrayLists to comma-separated strings
//            String prereq = String.join(", ", courseprereq);

                for (int m=0 ; m<s.getCourses().size() ; m++ ) {
                if (s.getCourses().get(m) !=null ) {
     
                Object[] rowData = {
                   "  -    " + s.getCourses().get(m).getCourseCode(),
                   "-  " +  s.getCourses().get(m).getCoursename(),
                  "-   " + s.getCourses().get(m).getCredit() ,
                "-   " +  s.getCourses().get(m).getGPA() 
                };
                model.addRow(rowData);
            }
            }
}



private course findCourseByCode(int courseCode) {
    for (course Course : arrays.courses) {
        if (Course != null && Course.getCoursecode() == courseCode) {
            return Course;
        }
    }
    return null;
}


    private void facAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_facAncestorAdded
        int id = arrays.Students[Login_Student.getM()].getId();
        fac.setText(Integer.toString(id));
    }//GEN-LAST:event_facAncestorAdded

    private void fac1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fac1AncestorAdded
        String faculty = arrays.Students[Login_Student.getM()].getFaculty().getName();
        fac1.setText(faculty);
    }//GEN-LAST:event_fac1AncestorAdded

    private void fac2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fac2AncestorAdded
        int size = arrays.Students[Login_Student.getM()].getCourses().size();
        fac2.setText(Integer.toString(size));
    }//GEN-LAST:event_fac2AncestorAdded

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        /*DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String[] columnNames = {"UserName", "Faculty", "ID"};
        model.setColumnIdentifiers(columnNames);

        for (student ss : Students) {
            if (ss != null) {
                Object[] rowData = {ss.getUsername(), ss.getFaculty(), ss.getId()};
                model.addRow(rowData);
            }
        }

        JScrollPane scrollPane = new JScrollPane(jTable1);
        jPanel4.add(scrollPane);
         */
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jLabel63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel63MouseClicked

    private void jLabel63MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel63MouseMoved

    private void jLabel64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel64MouseClicked

    private void jLabel64MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel64MouseMoved

    private void fac3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fac3AncestorAdded
        double size = arrays.Students[Login_Student.getM()].getGPA();
        fac3.setText(Double.toString(size));
    }//GEN-LAST:event_fac3AncestorAdded

    private void fac4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fac4AncestorAdded
        int size = (int) arrays.Students[Login_Student.getM()].getEnrolledYear();
        fac4.setText(Integer.toString(size));
    }//GEN-LAST:event_fac4AncestorAdded

    private void jPanel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseMoved
        setcolor(jPanel8);
        resetcolor(jPanel14);
        resetcolor(jPanel15);

        jPanel8.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel8MouseMoved

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        new studentDash ().setVisible(true);
        setVisible (false) ;
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel19MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseMoved
        jPanel19.setBackground(new Color (153,0,0));

        jPanel19.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel19MouseMoved

    private void jPanel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseClicked
        new Welcome_Page().setVisible(true);
        new Login_Student().setVisible(true);
    }//GEN-LAST:event_jPanel19MouseClicked

    private void jPanel15MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseMoved
        setcolor(jPanel15);
        resetcolor(jPanel14);
        resetcolor(jPanel8);
        jPanel15.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel15MouseMoved

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
setVisible (false) ; 
new studentAbout ().setVisible(true);

    }//GEN-LAST:event_jPanel15MouseClicked

    private void jPanel14MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseMoved

        setcolor(jPanel14);
        resetcolor(jPanel15);
        resetcolor(jPanel8);

        jPanel14.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel14MouseMoved

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
new studentCourses ().setVisible(true);

        setVisible (false) ; 

    }//GEN-LAST:event_jPanel14MouseClicked

    private void user1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_user1AncestorAdded
        try {
            userr = arrays.Students[Login_Student.getM()].getUsername();
            user1.setText(userr);
        } catch (java.lang.NullPointerException sww) {
        }

        /*
        try {
            user () ;
            user.setText(adminstration.admins[m].getUsername());
        } catch ( java.lang.StackOverflowError ss ) {
        }
        */
    }//GEN-LAST:event_user1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new studentDash().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back;
    private javax.swing.JLabel fac;
    private javax.swing.JLabel fac1;
    private javax.swing.JLabel fac2;
    private javax.swing.JLabel fac3;
    private javax.swing.JLabel fac4;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel user1;
    // End of variables declaration//GEN-END:variables
}
